spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: false

server:
  ssl:
    enabled: false
  port: '8084'
  address: 0.0.0.0

cors:
  allowedOriginsPattern: http://192.168.25.46:9000

# halconfig

redis:
  connection: ${services.redis.baseUrl:redis://localhost:6379}

logging:
  level:
    root: INFO
