server:
  tomcat:
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
    internalProxies: .*
#    httpsServerPort: X-Forwarded-Port

security:
  basic:
    enabled: true
  user: {}

#  oauth2:
#    enabled: false
#    client:
#      clientId: spinnaker-oauth
#      clientSecret: 571992e2-b77f-42f3-b929-b6492af2db4d
#      userAuthorizationUri: http://www.313.co.kr/auth/realms/master/protocol/openid-connect/auth
#      accessTokenUri: http://www.313.co.kr/auth/realms/master/protocol/openid-connect/token
#    resource:
#      userInfoUri: http://www.313.co.kr/auth/realms/master/protocol/openid-connect/userinfo
#    userInfoMapping:
#      email: email
#      firstName: given_name
#      lastName: family_name
#      username: preferred_username
#    provider: other
saml:
  enabled: true
  metadataUrl: file:/opt/spinnaker/config/idp-metadata.xml
  issuerId: spinnaker-saml
  keyStore: file:/opt/spinnaker/config/saml.jks
  keyStorePassword:
  keyStoreAliasName: saml
  redirectProtocol: http
  redirectHostname: 192.168.25.46:8084
  userAttributeMapping:
    roles: memberOf

services:
  fiat:
    baseUrl: "http://fiat:7003"
    enabled: true
